### ISSUE TITLE
a bug while changing non-default version of GEMC and XERCES

### ISSUE THREAD

**Issue by zhaozhiwen** [JeffersonLab/ceInstall#1]
---

setenv GEMC_VERSION test
setenv XERCES_VERSION test
setenv JLAB_VERSION 1.3
setenv JLAB_ROOT /home/zwzhao/apps/jlab_root
## source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh  "keepmine" 

This won't change version for GEMC nor XERCES, but it works for all other packages

only tested for ceinstall 1.3

**Comment by maureeungaro** [comment]
fixed in devel
