### ISSUE TITLE
The QT version for GEANT4 is not correctly found in go_geant4

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/ceInstall#5]
Seems this keeps coming back.

The version of QT that can be found using the cmake file findQT4.cmake will only work with QT4, and we are on QT5.x. It used to work to specify the:
`     -DQT_QMAKE_EXECUTABLE=$QTDIR/bin/qmake`
but this no longer works. What is needed now is:
`    -DCMAKE_PREFIX_PATH=$QTDIR/lib/cmake`

Works on my Mac, QT5.8.0 and GEANT4.10.02.p03

**Comment by maureeungaro** [comment]
Hi Maurik, 

go_geant4 -DQT_QMAKE_EXECUTABLE=$QTDIR/bin/qmake  works with qt 5.1 and above - assuming the env is set with ceInstall and qt is installed with go_qt. 

It works on Mac, RHEL7, CentOS7 and Ubuntu. Are you getting any error with this procedure?

**Comment by maureeungaro** [comment]
Issue is not present using reinstall 2.1 and 2.2 on Sierra and High Sierra. Cannot reproduce this problem.
